core {
  app {
    directory = "${?user.home}/.jbox"
    json-dir = "${core.app.directory}/configs"
    app-config = "${core.app.directory}/json.config"
  }

  database {
    path = "${core.app.directory}/data.db"
  }
}
