syntax = "proto3";

option java_package = "core.grpc";
option java_multiple_files = true;

package core.config;

service ConnectionConfigService {
  rpc ListConfigs(Empty) returns (ConfigList);
  rpc AddConfigFromUri(ConfigUriInput) returns (ConfigResponse);
  rpc AddConfigFromJson(ConfigJsonInput) returns (ConfigResponse);
  rpc DeleteConfig(ConfigId) returns (Empty);
  rpc GetActiveConfig(Empty) returns (ActiveConfigResponse);
  rpc SetActiveConfig(ConfigId) returns (Empty);
  rpc RenameConfig(RenameConfigRequest) returns (Empty);
}

message Empty {}

message ConfigUriInput {
  string name = 1;
  string uri = 2;
}

message ConfigJsonInput {
  string name = 1;
  string jsonPath = 2;
}

message ConfigResponse {
  int32 id = 1;
}

message ConfigId {
  int32 id = 1;
}

message Config {
  int32 id = 1;
  string name = 2;
  string jsonPath = 3;
}

message ConfigList {
  repeated Config configs = 1;
}

message ActiveConfigResponse {
  Config config = 1;
}

message RenameConfigRequest {
  int32 id = 1;
  string newName = 2;
}
